language: objective-c
xcode_project: STURITemplate.xcodeproj
matrix:
    include:
        - xcode_sdk: iphonesimulator7.1
          xcode_scheme: STURITemplate-ios
        - xcode_sdk: iphonesimulator8.1
          xcode_scheme: STURITemplate-ios
        - xcode_sdk: macosx
          xcode_scheme: STURITemplate-mac
branches:
    only:
        - master
before_script:
    - brew update && brew upgrade xctool
